config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doit/', include('doit.urls')),
]

doit/urls.py
from django.urls import path

from . import views

app_name = 'doit'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:doit_item_id>/', views.detail, name="detail"),
    path('create/item/', views.create_item, name="create_item"),
    path('finish/<int:doit_item_id>', views.finish_item, name="finish_item"),
    path('delete/<int:doit_item_id>', views.delete_item, name="delete_item"),
    path('back/<int:doit_item_id>', views.back_item, name="back_item"),
]

doit/models.py
from django.db import models

# Create your models here.
class DOITLIST(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    done_date = models.DateTimeField()
    is_done = models.BooleanField()
    
    def __str__(self):
        return self.subject

doit/forms.py
from django import forms

from doit.models import DOITLIST

class DOITLISTDetailForm(forms.ModelForm):
    class Meta:
        model = DOITLIST
        fields = ['subject', 'content', 'create_date', 'done_date', 'is_done']
        
        labels = {
            'subject': '제목',
            'content': '내용',
            'create_date': '생성일자',
            'done_date': '완료일자',
            'is_done': '완료 여부'          
        }
        
class DOITLISTCreateForm(forms.ModelForm):
    class Meta:
        model = DOITLIST
        fields = ['subject', 'content', 'done_date']
        
        labels = {
            'subject': '제목',
            'content': '내용',
            'done_date': '완료일자',      
        }

doit/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .models import DOITLIST
from .forms import DOITLISTDetailForm, DOITLISTCreateForm

# Create your views here.
def index(request):
    todo_list = DOITLIST.objects.filter(is_done__exact=False).order_by('done_date')
    done_list = DOITLIST.objects.filter(is_done__exact=True).order_by('done_date')
    
    context = {
        'todo_list': todo_list,
        'done_list': done_list,
    }
    
    return render(request, 'doit/doitlist.html', context)

def detail(request, doit_item_id):
    doit_item = get_object_or_404(DOITLIST, pk=doit_item_id)
    if request.method == "POST":
        form = DOITLISTDetailForm(request.POST, instance=doit_item)
        if form.is_valid():
            doit_item = form.save(commit=False)
            doit_item.save()
            return redirect('doit:index')
    else:
        form = DOITLISTDetailForm(instance=doit_item)
        
    context = {
        'form': form
    }
    return render(request, 'doit/detail_form.html', context=context)

def create_item(request):
    if request.method == "POST":
        form = DOITLISTCreateForm(request.POST)
        if form.is_valid():
            doit_item = form.save(commit=False)
            doit_item.create_date = timezone.now()
            doit_item.is_done = False
            doit_item.save()
            return redirect('doit:index')
    else:
        form = DOITLISTCreateForm()
    context = {
        'form': form
    }
    return render(request, 'doit/create_form.html', context=context)

def finish_item(request, doit_item_id):
    doit_item = get_object_or_404(DOITLIST, pk=doit_item_id)
    doit_item.is_done = True
    doit_item.save()
    return redirect('doit:index')

def delete_item(request, doit_item_id):
    doit_item = get_object_or_404(DOITLIST, pk=doit_item_id)
    doit_item.delete()
    return redirect('doit:index')
    
def back_item(request, doit_item_id):
    doit_item = get_object_or_404(DOITLIST, pk=doit_item_id)
    doit_item.is_done = False
    doit_item.save()
    return redirect('doit:index')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- Bootstrap Icon -->
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
        <!-- custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>Do IT!</title>
    </head>
    
    <body>
    {% include "navbar.html" %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    
    {% block script %}
    {% endblock %}
    <script type="text/javascript" src="{% static 'bootstrap.min.js' %}"></script>
    </body>
</html>

templates/doit/create_form.html
{% extends "base.html" %}
{% load doit_filter %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">작성하기</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <!-- 제목 -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
            <!-- 생성 일자 -->
            <div class="mb-3">
                <label for="create_date" class="form-label">생성일자 <i>format: YYYY-MM-DD HH:MM:SS</i></label>
                <input type="text" class="form-control" name="create_date" id="create_date" value="" readonly>
            </div>
        <!-- 완료 일자 -->
        <div class="mb-3">
            <label for="done_date" class="form-label">완료일자 <i>format: YYYY-MM-DD HH:MM:SS</i></label>
            <input type="date|time" class="form-control" name="done_date" id="done_date" value="{{ form.done_date.value|default_if_none:'' }}">
        </div>
        <!-- 내용 -->
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
    
</div>
{% endblock  %}
{% block script %}
<script type="text/javascript">
    const create_time_item = document.getElementById('create_date')
    function setTime(){
        var now = new Date()
        date = [now.getFullYear(), now.getMonth()+1, now.getDate()]
        time = [now.getHours(), now.getMinutes(), now.getSeconds()]
        str_now = date.join('-') + ' ' + time.join(':')
        create_time_item.value = str_now
    }
    setTime()
    setInterval(setTime, 1000)
  </script>
{% endblock %}

templates/doit/detail_form.html
{% extends "base.html" %}
{% load doit_filter %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">상세보기</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <!-- 제목 -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <!-- 생성 일자 -->
        <div class="mb-3">
            <label for="create_date" class="form-label">생성일자 <i>format: YYYY-MM-DD HH:MM:SS</i></label>
            <input type="text" class="form-control" name="create_date" id="create_date" value="{{ form.create_date.value|date:'Y-m-d H:i:s' }}" readonly>
        </div>
        <!-- 완료 일자 -->
        <div class="mb-3">
            <label for="done_date" class="form-label">완료일자 <i>format: YYYY-MM-DD HH:MM:SS</i></label>
            <input type="text" class="form-control" name="done_date" id="done_date" value="{{ form.done_date.value|date:'Y-m-d H:i:s' }}">
        </div>
        <!-- 내용 -->
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <!-- 완료여부 -->
        <div class="mb-3 form-check form-switch">
            <input type="checkbox" class="form-check-input" name="is_done" id="is_done" {% if form.is_done.value %} checked {% endif %}>
            <label for="is_done" class="form-check-label">완료여부</label>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
    
</div>
{% endblock  %}

templates/doit/doitlist.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
<div class="container my-3">
    <div class="d-flex">
        <div class="flex-grow-1 bg-light rounded-2 p-2 me-1 w-50">
            <div class="d-flex align-items-center">
                <h2>TODO</h2>
                <div >
                    <a class="btn btn-primary btn-sm mb-2 ms-1 text-nowrap" href="{% url 'doit:create_item' %}"><i class="bi bi-plus text-white"></i></a>
                </div>
            </div>
            <table class="table">
                <thead>
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">제목</th>
                        <th scope="col">마감기한</th>
                        <th scope="col">완료 / 삭제</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_item in todo_list %}
                    <tr class="text-center">
                        <td scope="row">{{ forloop.counter }}</td>
                        <td><a class="" href="{% url 'doit:detail' todo_item.id %}">{{ todo_item.subject }}</a></td>
                        <td>{{ todo_item.done_date|naturaltime }}</td>
                        <td>
                            <a class="btn btn-sm btn-success me-1" href="{% url 'doit:finish_item' todo_item.id %}"><i class="bi bi-check"></i></a>
                            <a class="btn btn-sm btn-danger" href="{% url 'doit:delete_item' todo_item.id %}"><i class="bi bi-x"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>

        <div class="flex-grow-1 bg-light rounded-2 p-2 w-50">
            <h2>DONE</h2>
            <table class="table">
                <thead>
                    <tr class="text-center">
                        <th scope="col">#</th>
                        <th scope="col">제목</th>
                        <th scope="col">마감기한</th>
                        <th scope="col">미완료 / 삭제</th>
                    </tr>
                </thead>
                <tbody>
                    {% for done_item in done_list %}
                    <tr class="text-center">
                        <td scope="row">{{ forloop.counter }}</td>
                        <td><a class="" href="{% url 'doit:detail' done_item.id %}">{{ done_item.subject }}</a></td>
                        <td>{{ done_item.done_date|naturaltime }}</td>
                        <td>
                            <a class="btn btn-sm btn-warning", href="{% url 'doit:back_item' done_item.id %}"><i class="bi bi-box-arrow-in-left"></i></a>
                            <a class="btn btn-sm btn-danger" href="{% url 'doit:delete_item' done_item.id %}"><i class="bi bi-x"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock  %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container">
        <div>
            <a class="navbar-brand" href="{% url 'doit:index' %}">
                <i class="bi bi-card-checklist"></i> DO IT!
            </a>
        </div>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>